service: ruby-asw-lambda-image-processing

provider:
  name: aws
  runtime: ruby2.5
  region: # AWS region conde, e.g. eu-central-1
  deploymentBucket:
    name: # Name of bucket where script will be uploaded, e.g. my-ruby-asw-lambda-image-processing-bucket
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
   handle_resize:
     handler: handler.ImageHandler.process
     events:
       - s3:
           bucket: # Name of bucket where images will be uploaded, e.g. my-upload-bucket
           event: s3:ObjectCreated:*
